listener 1883
allow_anonymous false
password_file /mosquitto/data/mqtt_users.txt
log_dest file /mosquitto/log/mosquitto.log
log_timestamp true
log_timestamp_format %Y-%m-%d %H:%M:%S
log_type error
log_type warning
log_type notice
log_type information
