#!/usr/bin/env bash
#
# mediamtx-users.sh
#
# Generates config/users.env — the MediaMTX internal-authentication user
# database, as MTX_AUTHINTERNALUSERS_* environment variables that compose
# hands to the container. Passwords are hashed with argon2id; the plaintext
# never reaches disk.
#
# Targets:
#   - macOS                        (Homebrew)
#   - Debian / Ubuntu / Pi OS      (apt-get)
#   - Fedora / RHEL / Rocky / Alma (dnf)
#
# Usage:  ./mediamtx-users.sh [-f|--file PATH] [-h|--help]
# Do not run as root.  Needs a TTY: every value comes from a prompt.
#
# The script is idempotent in the sense that matters: it shows you what is
# already in the file before it touches it, and asks whether this run appends
# to that list or replaces it. An overwrite takes a timestamped backup first.
#
# Turning authentication on takes two more steps the script cannot do for you,
# because both are decisions: uncomment `authMethod` and `authInternalUsers`
# in config/mediamtx.yml, then `docker compose up -d`. The closing NEXT lines
# repeat them, and the script warns if either looks undone.
# ‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒

set -eo pipefail

# ‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒
#                                                                       GLOBALS
# ‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
USERS_FILE="$SCRIPT_DIR/config/users.env"
MEDIAMTX_YML="$SCRIPT_DIR/config/mediamtx.yml"
COMPOSE_FILE="$SCRIPT_DIR/compose.yaml"

MIN_PASS_LEN=6
ARGON2_HASH_LEN=32          # -l 32, matching the MediaMTX documentation
SALT_LEN=16                 # argon2 refuses a salt under 8 bytes

OS=""
PKG_MGR=""
SUDO=""

# Collected users, one parallel-array slot each. PERMS holds newline-joined
# "action|path" pairs; a path of "" means every path.
ENTRY_USER=()
ENTRY_PASS=()
ENTRY_IPS=()
ENTRY_PERMS=()
ENTRY_ORIGIN=()             # "kept" for entries read back, "new" for this run

MODE=""                     # append | overwrite
HAD_FILE=0                  # so the write step does not claim it replaced nothing
WROTE_FILE=0                # so the CTRL-C trap does not lie about the file
ADDED_THIS_RUN=0
STTY_SAVED=""               # terminal state to restore if we die mid-password
PASSWORD_IN=""              # ask_password's out-parameter; see the note there

# ‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒
#                                PRETTY OUTPUT — IT DOJO TERMINAL DESIGN SYSTEM
# ‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒
# Copied verbatim from ~/projects/qol/linux/base_functions.sh, the canonical
# block, because that library is Linux-only and this script also runs on macOS.
# Copy it whole or not at all — a partial copy is a restyle. Palette and rules:
#   ~/vaults/dojobrain/30-references/design-system/itdojo-terminal-design-system.md
# Decide color and depth once. Re-callable so tests can force a tier.
#   NO_COLOR         — set to disable color entirely (wins over everything)
#   QOL_FORCE_COLOR  — set to keep color when stdout is not a TTY (e.g. less -R)
#   QOL_COLOR_DEPTH  — truecolor (default) | 256 | 8 | none
# Several inks have no reader in any one script that carries this block —
# a token ink with no consumer is suppressed, not deleted, because dropping a
# color from a palette copy makes it a worse copy.
# shellcheck disable=SC2034
qol_init_color() {
    if [[ -n "${NO_COLOR:-}" ]]; then
        QOL_COLOR=""
    elif [[ -n "${QOL_FORCE_COLOR:-}" || -t 1 ]]; then
        QOL_COLOR=1
    else
        QOL_COLOR=""
    fi

    case "${QOL_COLOR_DEPTH:-truecolor}" in
        256)  QOL_DEPTH=256 ;;
        8)    QOL_DEPTH=8 ;;
        none) QOL_DEPTH=none ;;
        *)    QOL_DEPTH=truecolor ;;
    esac
    [[ -z "$QOL_COLOR" ]] && QOL_DEPTH=none

# ‒‒ generated by dojobrain scripts/build-design-tokens.py --emit-bash
# ‒‒ do not hand-edit; edit tokens/colors.css and re-emit.
    case "$QOL_DEPTH" in
        truecolor)
            QOL_STEP=$'\033[38;2;188;176;232m'
            QOL_PASS=$'\033[38;2;78;206;106m'
            QOL_INFO=$'\033[38;2;122;160;216m'
            QOL_WARN=$'\033[38;2;224;180;90m'
            QOL_STOP=$'\033[38;2;224;107;130m'
            QOL_FG=$'\033[38;2;228;222;245m'
            QOL_META=$'\033[38;2;154;147;181m'
            QOL_RULE=$'\033[38;2;74;65;112m'
            QOL_SEL=$'\033[48;2;36;29;61m'
            QOL_OKBG=$'\033[48;2;21;50;31m'
            ;;
        256)
            QOL_STEP=$'\033[38;5;140m'
            QOL_PASS=$'\033[38;5;77m'
            QOL_INFO=$'\033[38;5;110m'
            QOL_WARN=$'\033[38;5;179m'
            QOL_STOP=$'\033[38;5;168m'
            QOL_FG=$'\033[38;5;189m'
            QOL_META=$'\033[38;5;103m'
            QOL_RULE=$'\033[38;5;60m'
            QOL_SEL=$'\033[48;5;235m'
            QOL_OKBG=$'\033[48;5;22m'
            ;;
        8)
            QOL_STEP=$'\033[94m'
            QOL_PASS=$'\033[92m'
            QOL_INFO=$'\033[94m'
            QOL_WARN=$'\033[93m'
            QOL_STOP=$'\033[91m'
            QOL_FG=$'\033[97m'
            QOL_META=$'\033[90m'
            QOL_RULE=$'\033[90m'
            QOL_SEL=$'\033[7m'
            QOL_OKBG=$'\033[7m'
            ;;
        *)
            QOL_STEP="" QOL_PASS="" QOL_INFO="" QOL_WARN="" QOL_STOP="" QOL_FG="" QOL_META="" QOL_RULE="" QOL_SEL="" QOL_OKBG=""
            ;;
    esac
# ‒‒ end generated block

    if [[ "$QOL_DEPTH" == "none" ]]; then
        QOL_BOLD="" QOL_DIM="" QOL_RESET=""
    else
        QOL_BOLD=$'\033[1m'; QOL_DIM=$'\033[2m'; QOL_RESET=$'\033[0m'
    fi
}
qol_init_color

# Terminal width, falling back to 80 with no TTY (cron, CI, pipes).
#
# Ask the terminal, not terminfo. `tput cols 2>/dev/null` inside a command
# substitution answers 80 however wide the window is: with stdout captured,
# ncurses reads the window size off stderr instead, and that redirect throws
# the only usable fd away. Every rule, bookend and selection bar in this file
# was pinned to 80 columns by it. stty asks /dev/tty directly, so no amount of
# nesting can hide the answer. COLUMNS still wins when set, as an override.
_term_cols() {
    local cols="${COLUMNS:-}"
    if [[ ! "$cols" =~ ^[0-9]+$ ]] || (( cols <= 0 )); then
        cols="$(stty size </dev/tty 2>/dev/null | cut -d' ' -f2)"
    fi
    if [[ ! "$cols" =~ ^[0-9]+$ ]] || (( cols <= 0 )); then
        cols=80
    fi
    printf '%s' "$cols"
}

# Repeat a character n times. Emits nothing for n <= 0.
_repeat() {
    local ch="$1" n="$2" line
    [[ "$n" =~ ^-?[0-9]+$ ]] || return 0
    (( n <= 0 )) && return 0
    printf -v line '%*s' "$n" ''
    printf '%s' "${line// /$ch}"
}

# One milestone line. The prefix is exactly 9 columns: gutter, space,
# 4-char badge, 3 spaces. Message text therefore starts at column 10.
_log_line() {
    local ink="$1" badge="$2" text="$3"
    printf '%s%s▌ %-4s   %s%s\n' "$QOL_BOLD" "$ink" "$badge" "$text" "$QOL_RESET"
}

log_step() { _log_line "$QOL_STEP" STEP "$1"; }
log_ok()   { _log_line "$QOL_PASS" PASS "$1"; }
log_info() { _log_line "$QOL_INFO" INFO "$1"; }
log_warn() { _log_line "$QOL_WARN" WARN "$1"; }
log_err()  { _log_line "$QOL_STOP" STOP "$1" >&2; }
log_ask()  { _log_line "$QOL_STEP" ASK  "$1"; }
log_next() { _log_line "$QOL_INFO" NEXT "$1"; }

# Phase boundary: a gray rule carrying the phase name in violet. A rule now
# means "new phase", which is information; a rule per line meant nothing.
log_phase() {
    local title="$1" cols fill
    cols="$(_term_cols)"
    fill=$(( cols - ${#title} - 4 ))
    printf '\n%s──%s %s%s%s%s %s%s\n\n' \
        "$QOL_RULE" "$QOL_RESET" \
        "$QOL_BOLD$QOL_STEP" "$title" "$QOL_RESET" \
        "$QOL_RULE" "$(_repeat '─' "$fill")" "$QOL_RESET"
}

# Run bookends. Jade rules, so a run's edges are findable when scrolling
# back through screens of package-manager output; phase rules are gray.
banner() {
    local title="$1" sub="${2:-}" cols
    cols="$(_term_cols)"
    printf '%s%s%s\n' "$QOL_PASS" "$(_repeat '━' "$cols")" "$QOL_RESET"
    printf '  %s%s⛩ %s ⛩%s' "$QOL_BOLD" "$QOL_PASS" "$title" "$QOL_RESET"
    [[ -n "$sub" ]] && printf '   %s%s%s' "$QOL_META" "$sub" "$QOL_RESET"
    printf '\n%s%s%s\n' "$QOL_PASS" "$(_repeat '━' "$cols")" "$QOL_RESET"
}

# NOTE: not named `complete` — that is a bash builtin.
log_complete() {
    local title="$1" cols
    cols="$(_term_cols)"
    printf '\n%s%s%s\n' "$QOL_PASS" "$(_repeat '━' "$cols")" "$QOL_RESET"
    printf '  %s%s%s ⛩ %s ⛩ %s\n' "$QOL_OKBG" "$QOL_BOLD" "$QOL_PASS" "$title" "$QOL_RESET"
    printf '%s%s%s\n\n' "$QOL_PASS" "$(_repeat '━' "$cols")" "$QOL_RESET"
}

# ‒‒ Back-compat ‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒
# Eight other scripts call these. Kept working, not kept identical: printline
# no longer appears in any log_* line, because the design uses phase rules.

# Print a separator line the width of the terminal.
# Usage: printline [solid|bullet|ibeam|star|plus|diamond|dentistry]
printline() {
    local sep
    case "${1:-solid}" in
        bullet)    sep="•" ;;
        ibeam)     sep="⌶" ;;
        star)      sep="★" ;;
        plus)      sep="✛" ;;
        diamond)   sep="◆" ;;
        dentistry) sep="⏥" ;;
        *)         sep="─" ;;
    esac
    printf '%s%s%s\n' "$QOL_RULE" "$(_repeat "$sep" "$(_term_cols)")" "$QOL_RESET"
}

# Print styled text with no separator. Also usable inline via command
# substitution: echo "I am a $(style_text "Raspberry Pi" bold wine)."
# Usage: style_text "text" [normal|bold|light] [brand or legacy color name]
# Brand names:  violet jade steel saffron wine prose meta rule
# Legacy names: blue   green  —     yellow  red   —     —    —
style_text() {
    local text="$1" weight="${2:-normal}" color="${3:-}"
    local wt="" ink=""
    case "$weight" in
        bold)  wt="$QOL_BOLD" ;;
        light) wt="$QOL_DIM" ;;
    esac
    case "$color" in
        violet)        ink="$QOL_STEP" ;;
        jade|green)    ink="$QOL_PASS" ;;
        steel|blue)    ink="$QOL_INFO" ;;
        saffron|yellow) ink="$QOL_WARN" ;;
        wine|red)      ink="$QOL_STOP" ;;
        prose)         ink="$QOL_FG" ;;
        meta)          ink="$QOL_META" ;;
        rule)          ink="$QOL_RULE" ;;
    esac
    if [[ -z "$QOL_COLOR" ]] || [[ -z "$ink" && -z "$wt" ]]; then
        printf '%s\n' "$text"
        return 0
    fi
    printf '%s%s%s%s\n' "$wt" "$ink" "$text" "$QOL_RESET"
}

# Separator + styled text. Retained for callers that predate log_phase;
# new code should use log_phase or a log_* helper instead.
format_font() {
    printline
    style_text "$1" "${2:-bold}" "${3:-saffron}"
}

# Banner for script titles. Prefer banner/log_complete in new code.
log_title() {
    local cols
    cols="$(_term_cols)"
    printf '%s%s%s\n' "$QOL_PASS" "$(_repeat '━' "$cols")" "$QOL_RESET"
    style_text "$1" bold jade
    printf '%s%s%s\n' "$QOL_PASS" "$(_repeat '━' "$cols")" "$QOL_RESET"
}

# ‒‒ Interactive ‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒
# Three question shapes, sharing gotime's chrome. Prompts go to stderr so
# ask_value and ask_choice can be captured with $(...). All three skip the
# prompt and return the default when ASSUME_YES is set or stdin is not a
# TTY — the priority order install_nano.sh already follows.

# Decode one keypress into _KEY (and _KEYCH for digits). Bash 3.2 safe:
# no read -N, no fractional -t. Arrows arrive as ESC then "[A"/"OA".
_read_key() {
    local k s
    _KEY=""; _KEYCH=""
    IFS= read -rsn1 k || { _KEY="QUIT"; return 0; }
    if [[ -z "$k" ]]; then _KEY="ENTER"; return 0; fi
    case "$k" in
        $'\r'|$'\n') _KEY="ENTER" ;;
        $'\x1b')
            s=""
            IFS= read -rsn2 -t 1 s
            case "$s" in
                '[A'|'OA') _KEY="UP" ;;
                '[B'|'OB') _KEY="DOWN" ;;
                '')        _KEY="QUIT" ;;
                *)         _KEY="OTHER" ;;
            esac ;;
        [0-9]) _KEY="DIGIT"; _KEYCH="$k" ;;
        k|K)   _KEY="UP" ;;
        j|J)   _KEY="DOWN" ;;
        q|Q)   _KEY="QUIT" ;;
        *)     _KEY="OTHER" ;;
    esac
    return 0
}

# ask_confirm "question" [Y|N]  ->  exit 0 for yes, 1 for no
ask_confirm() {
    local q="$1" def="${2:-N}" hint reply
    if [[ -n "${ASSUME_YES:-}" ]]; then return 0; fi
    if [[ ! -t 0 ]]; then [[ "$def" == "Y" ]]; return $?; fi
    if [[ "$def" == "Y" ]]; then hint="Y/n"; else hint="y/N"; fi
    _log_line "$QOL_STEP" ASK "$q" >&2
    printf '    %s❯%s %s[%s]%s ' "$QOL_PASS" "$QOL_RESET" "$QOL_META" "$hint" "$QOL_RESET" >&2
    read -r reply
    reply="${reply:-$def}"
    case "$reply" in [Yy]*) return 0 ;; *) return 1 ;; esac
}

# ask_value "question" "default" ["hint"]  ->  echoes the answer
ask_value() {
    local q="$1" def="$2" hint="${3:-}" reply
    if [[ -n "${ASSUME_YES:-}" || ! -t 0 ]]; then printf '%s' "$def"; return 0; fi
    _log_line "$QOL_STEP" ASK "$q" >&2
    [[ -n "$hint" ]] && printf '         %s%s%s\n' "$QOL_META" "$hint" "$QOL_RESET" >&2
    printf '    %s❯%s [%s%s%s] ' "$QOL_PASS" "$QOL_RESET" "$QOL_PASS" "$def" "$QOL_RESET" >&2
    read -r reply
    printf '%s' "${reply:-$def}"
}

# Draw the choice list. Emits exactly (count + 3) lines so the caller knows
# how far to move the cursor back up when redrawing.
_ask_choice_draw() {
    local heading="$1" sel="$2"; shift 2
    local i=0 item label hint plain pad cols
    cols="$(_term_cols)"
    printf '\n %s%s%s%s\n' "$QOL_BOLD" "$QOL_STEP" "$heading" "$QOL_RESET"
    for item in "$@"; do
        label="${item%%|*}"
        hint="${item#*|}"; [[ "$hint" == "$item" ]] && hint=""
        # Pad every row out to the full width with real spaces. The selection
        # bar has to reach the right edge, and CLR_EOL cannot carry it there:
        # screen and tmux report no `bce`, so ESC[K erases to the default
        # background and cuts the bar off where the text ended. Padding the
        # unselected rows is what paints over the bar as it moves away.
        # Three leading columns in both branches: " ❯ " when selected, three
        # spaces when not. Measure the same shape the row actually prints.
        printf -v plain '   %2d   %-18s %s' "$(( i + 1 ))" "$label" "$hint"
        pad=$(( cols - ${#plain} ))
        (( pad < 0 )) && pad=0
        if (( i == sel )); then
            printf '%s%s%s ❯ %2d   %-18s %s%*s%s\n' \
                "$QOL_SEL" "$QOL_BOLD" "$QOL_PASS" "$(( i + 1 ))" "$label" "$hint" \
                "$pad" '' "$QOL_RESET"
        else
            printf '   %s%2d%s   %s%-18s%s %s%s%s%*s\n' \
                "$QOL_META" "$(( i + 1 ))" "$QOL_RESET" \
                "$QOL_FG" "$label" "$QOL_RESET" "$QOL_META" "$hint" "$QOL_RESET" \
                "$pad" ''
        fi
        i=$(( i + 1 ))
    done
    printf ' %s↑/↓%s or %sj/k%s move   %s1-9%s jump   %s⏎%s select\n' \
        "$QOL_PASS" "$QOL_RESET" "$QOL_PASS" "$QOL_RESET" \
        "$QOL_PASS" "$QOL_RESET" "$QOL_PASS" "$QOL_RESET"
}

# ask_choice "HEADING" default_index "label|hint" [...]  ->  echoes 1-based index
# Redraws in place rather than taking the alternate screen: an installer that
# blanks the scrollback has destroyed the record of what it just did.
ask_choice() {
    local heading="$1" def="$2"; shift 2
    local n=$#
    local sel=$(( def - 1 ))
    if [[ -n "${ASSUME_YES:-}" || ! -t 0 ]]; then printf '%s' "$def"; return 0; fi
    _ask_choice_draw "$heading" "$sel" "$@" >&2
    while true; do
        _read_key
        case "$_KEY" in
            ENTER) break ;;
            QUIT)  sel=$(( def - 1 )); break ;;
            UP)    sel=$(( (sel - 1 + n) % n )) ;;
            DOWN)  sel=$(( (sel + 1) % n )) ;;
            DIGIT) if (( 10#$_KEYCH >= 1 && 10#$_KEYCH <= n )); then sel=$(( 10#$_KEYCH - 1 )); fi ;;
        esac
        printf '\033[%dA' $(( n + 3 )) >&2
        _ask_choice_draw "$heading" "$sel" "$@" >&2
    done
    printf '%s' "$(( sel + 1 ))"
}
# ‒‒ end theme block

# ‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒
#                                                                     ARGUMENTS
# ‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒

usage() {
    cat <<'USAGE'
mediamtx-users.sh — build the MediaMTX internal-auth user database

  ./mediamtx-users.sh [-f|--file PATH] [-h|--help]

  -f, --file PATH   write somewhere other than ./config/users.env
  -h, --help        this text

The script prints any users the file already holds, asks whether this run
appends to them or replaces them, then collects username, password, role,
path scope and source-IP allowlist for each new user. Passwords are hashed
with argon2id and never stored in the clear.

Authentication stays off until config/mediamtx.yml uncomments:

    authMethod: internal
    authInternalUsers: []
USAGE
}

parse_args() {
    while (( $# )); do
        case "$1" in
            -f|--file) [[ -n "${2:-}" ]] || { log_err "--file needs a path."; exit 1; }
                       USERS_FILE="$2"; shift 2 ;;
            -h|--help) usage; exit 0 ;;
            *)         log_err "Unknown argument: $1"; usage >&2; exit 1 ;;
        esac
    done
}

# ‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒
#                                                                        SAFETY
# ‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒

# ask_password turns terminal echo off around its reads. Dying in that window
# would hand the user back a shell that does not show what they type, so both
# traps restore the saved state before they say anything.
restore_tty() {
    [[ -n "$STTY_SAVED" ]] && stty "$STTY_SAVED" 2>/dev/null
    STTY_SAVED=""
    return 0
}

handle_ctrl_c() {
    restore_tty
    printf '\n' >&2
    if (( WROTE_FILE )); then
        log_warn "Interrupted after the file was written. $USERS_FILE is complete."
    else
        log_warn "Interrupted. Nothing was written."
    fi
    exit 130
}
trap handle_ctrl_c INT

handle_err() {
    local code=$? line="$1"
    restore_tty
    log_err "Failed at line $line (exit $code). $USERS_FILE was not modified."
    exit "$code"
}
trap 'handle_err $LINENO' ERR

check_for_root() {
    if [[ "${EUID:-$(id -u)}" -eq 0 ]]; then
        log_err "Do not run this as root. It writes a file you must own; rerun as yourself."
        exit 1
    fi
}

# Every value here comes from a prompt, and a password cannot have a default.
# ASSUME_YES would make ask_value hand back empty strings in silence, so the
# script refuses it outright rather than writing a user with no password.
require_interactive() {
    if [[ -n "${ASSUME_YES:-}" ]]; then
        log_err "ASSUME_YES is set. This script cannot run unattended — unset it and rerun."
        exit 1
    fi
    if [[ ! -t 0 || ! -t 1 ]]; then
        log_err "No TTY. Run this from a terminal, not a pipe or a cron job."
        exit 1
    fi
}

# ‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒
#                                                     PACKAGE MANAGER DETECTION
# ‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒

detect_package_manager() {
    OS="$(uname -s)"
    if [[ "$OS" == "Darwin" ]]; then
        PKG_MGR="brew"
        SUDO=""
    else
        if   command -v apt-get >/dev/null 2>&1; then PKG_MGR="apt-get"
        elif command -v dnf     >/dev/null 2>&1; then PKG_MGR="dnf"
        fi
        SUDO="sudo"
    fi
    if [[ -z "$PKG_MGR" ]]; then
        log_warn "No supported package manager found; argon2 must already be installed."
    else
        log_info "Platform: $OS, package manager $PKG_MGR."
    fi
}

pkg_install() {
    local pkg="$1"
    case "$PKG_MGR" in
        brew)    brew install "$pkg" ;;
        apt-get) $SUDO apt-get update -qq && $SUDO DEBIAN_FRONTEND=noninteractive apt-get install -y -qq "$pkg" ;;
        dnf)     $SUDO dnf install -y -q "$pkg" ;;
        *)       return 1 ;;
    esac
}

# ‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒
#                                                   ARGON2 (hashing dependency)
# ‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒

ensure_argon2() {
    if command -v argon2 >/dev/null 2>&1; then
        log_ok "argon2 is already installed."
        return 0
    fi
    log_info "argon2 hashes the passwords; it is a small standalone CLI."
    if ! ask_confirm "Install argon2 with $PKG_MGR?" Y; then
        log_err "argon2 is required. Install it and rerun:  $PKG_MGR install argon2"
        exit 1
    fi
    log_step "Installing argon2..."
    if ! pkg_install argon2 || ! command -v argon2 >/dev/null 2>&1; then
        log_err "argon2 did not install. Install it by hand and rerun."
        exit 1
    fi
    log_ok "argon2 is installed."
}

# argon2id at the CLI defaults (m=4096, t=3, p=1), matching what MediaMTX
# documents. Verification runs per request and HLS asks often, so a heavier
# profile costs the Pi on every segment, not once at login.
hash_password() {
    local pass="$1" salt
    salt="$(dd if=/dev/urandom bs=256 count=1 2>/dev/null \
            | LC_ALL=C tr -dc 'A-Za-z0-9' \
            | cut -c1-"$SALT_LEN")"
    if (( ${#salt} < 8 )); then
        log_err "Could not draw a $SALT_LEN-character salt from /dev/urandom."
        exit 1
    fi
    printf 'argon2:%s' "$(printf '%s' "$pass" | argon2 "$salt" -id -l "$ARGON2_HASH_LEN" -e)"
}

# ‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒
#                                    USERS FILE — READING WHAT IS ALREADY THERE
# ‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒

# Values are written single-quoted so Compose leaves the `$` in an argon2 hash
# alone. Strip the quotes on the way back in.
_unquote() {
    local v="$1"
    case "$v" in
        \'*\') v="${v#\'}"; v="${v%\'}" ;;
        \"*\") v="${v#\"}"; v="${v%\"}" ;;
    esac
    printf '%s' "$v"
}

_kv() {
    local f="$1" key="$2" v
    v="$(grep -m1 "^MTX_AUTHINTERNALUSERS_${key}=" "$f" 2>/dev/null || true)"
    [[ -z "$v" ]] && return 0
    _unquote "${v#*=}"
}

_indices() {
    sed -n 's/^MTX_AUTHINTERNALUSERS_\([0-9][0-9]*\)_.*/\1/p' "$1" | sort -n -u
}

_perm_indices() {
    sed -n "s/^MTX_AUTHINTERNALUSERS_$2_PERMISSIONS_\([0-9][0-9]*\)_.*/\1/p" "$1" | sort -n -u
}

# Load every user except the managed tail entry — render_users_file writes a
# fresh one, so keeping the old copy would duplicate it on every append.
load_existing() {
    local f="$1" i j u p ips act path perms
    for i in $(_indices "$f"); do
        u="$(_kv "$f" "${i}_USER")"
        [[ -z "$u" ]] && continue
        p="$(_kv "$f" "${i}_PASS")"
        ips="$(_kv "$f" "${i}_IPS")"
        perms=""
        for j in $(_perm_indices "$f" "$i"); do
            act="$(_kv "$f" "${i}_PERMISSIONS_${j}_ACTION")"
            [[ -z "$act" ]] && continue
            path="$(_kv "$f" "${i}_PERMISSIONS_${j}_PATH")"
            perms="${perms}${act}|${path}
"
        done
        if [[ "$u" == "any" && "$perms" == *"api|"* ]]; then
            continue
        fi
        ENTRY_USER+=("$u")
        ENTRY_PASS+=("$p")
        ENTRY_IPS+=("$ips")
        ENTRY_PERMS+=("$perms")
        ENTRY_ORIGIN+=("kept")
    done
}

perms_summary() {
    local perms="$1" line act path out=""
    while IFS= read -r line; do
        [[ -z "$line" ]] && continue
        act="${line%%|*}"; path="${line#*|}"
        [[ -z "$path" ]] && path="*"
        out="$out $act:$path"
    done <<< "$perms"
    printf '%s' "${out# }"
}

show_entries() {
    local i n
    n="${#ENTRY_USER[@]}"
    printf '         %s%-3s %-18s %-38s %-18s %s%s\n' \
        "$QOL_META" "IDX" "USER" "PERMISSIONS" "SOURCE IPS" "ORIGIN" "$QOL_RESET"
    for (( i = 0; i < n; i++ )); do
        printf '         %-3s %-18s %-38s %-18s %s\n' \
            "$i" "${ENTRY_USER[$i]}" \
            "$(perms_summary "${ENTRY_PERMS[$i]}")" \
            "${ENTRY_IPS[$i]:-any}" \
            "${ENTRY_ORIGIN[$i]}"
    done
}

# Decides MODE, and returns 1 when the user chose to walk away.
review_existing() {
    local choice
    if [[ ! -f "$USERS_FILE" ]]; then
        log_info "No users file yet — this run creates $USERS_FILE."
        MODE="overwrite"
        return 0
    fi
    load_existing "$USERS_FILE"
    if (( ${#ENTRY_USER[@]} == 0 )); then
        log_warn "$USERS_FILE exists but defines no users. Treating this run as a fresh write."
        MODE="overwrite"
        return 0
    fi
    HAD_FILE=1
    log_ok "$USERS_FILE already defines ${#ENTRY_USER[@]} user(s):"
    show_entries
    choice="$(ask_choice "THIS RUN SHOULD" 1 \
        "append|keep the users above and add more" \
        "overwrite|discard them; a timestamped backup is taken first" \
        "quit|change nothing and exit")"
    case "$choice" in
        1) MODE="append";    log_ok "Appending to the existing ${#ENTRY_USER[@]} user(s)." ;;
        2) MODE="overwrite"
           ENTRY_USER=(); ENTRY_PASS=(); ENTRY_IPS=(); ENTRY_PERMS=(); ENTRY_ORIGIN=()
           log_warn "Overwriting. The current file is backed up before it is replaced." ;;
        *) return 1 ;;
    esac
    return 0
}

# ‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒
#                                                QUESTIONS — ONE USER AT A TIME
# ‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒

user_exists() {
    local want="$1" i
    for (( i = 0; i < ${#ENTRY_USER[@]}; i++ )); do
        [[ "${ENTRY_USER[$i]}" == "$want" ]] && return 0
    done
    return 1
}

# This function's stdout IS its return value, so every complaint it makes goes
# to stderr — the same split ask_value already uses. A log_warn left on stdout
# would be captured and concatenated onto the username.
ask_username() {
    local u
    while true; do
        u="$(ask_value "Username" "" "letters, digits, dot, dash, underscore")"
        if [[ -z "$u" ]]; then
            log_warn "A username is required." >&2
        elif [[ ! "$u" =~ ^[A-Za-z0-9._-]+$ ]]; then
            log_warn "Use only letters, digits, dot, dash and underscore." >&2
        elif [[ "$u" == "any" ]]; then
            log_warn "\"any\" is reserved — MediaMTX reads it as the anonymous user." >&2
        elif user_exists "$u"; then
            log_warn "\"$u\" is already in this list. Pick another name." >&2
        else
            printf '%s' "$u"
            return 0
        fi
    done
}

# Not ask_value: it echoes what you type, and a password must not appear on
# screen or in the scrollback. Borrowing the chrome keeps the prompt identical
# to every other question while the read stays ours.
#
# Echo is killed with stty before the prompt is drawn, not left to `read -rs`.
# read only disables echo once it starts, so anything typed between the prompt
# printf and the read still lands on screen — a narrow window, but one a fast
# typist and every expect-driven test walks straight into.
#
# The answer comes back in PASSWORD_IN rather than on stdout, because $(...)
# would run all of this in a subshell and STTY_SAVED would die with it — and
# then a CTRL-C at the password prompt would hand back a shell with echo off.
ask_password() {
    local who="$1" p1 p2
    PASSWORD_IN=""
    STTY_SAVED="$(stty -g 2>/dev/null || true)"
    [[ -n "$STTY_SAVED" ]] && stty -echo 2>/dev/null
    while true; do
        _log_line "$QOL_STEP" ASK "Password for $who (minimum $MIN_PASS_LEN characters)" >&2
        printf '    %s❯%s %s[hidden]%s ' "$QOL_PASS" "$QOL_RESET" "$QOL_META" "$QOL_RESET" >&2
        IFS= read -rs p1; printf '\n' >&2
        if (( ${#p1} < MIN_PASS_LEN )); then
            log_warn "Too short — ${#p1} characters, minimum is $MIN_PASS_LEN."
            continue
        fi
        printf '    %s❯%s %sagain%s ' "$QOL_PASS" "$QOL_RESET" "$QOL_META" "$QOL_RESET" >&2
        IFS= read -rs p2; printf '\n' >&2
        if [[ "$p1" != "$p2" ]]; then
            log_warn "The two entries do not match."
            continue
        fi
        restore_tty
        PASSWORD_IN="$p1"
        return 0
    done
}

ask_role_perms() {
    local who="$1" choice path actions act out=""
    choice="$(ask_choice "ROLE FOR $who" 3 \
        "publisher|publish and read" \
        "viewer|read and play back recordings" \
        "full|publish, read and play back" \
        "admin|full, plus api, metrics and pprof")"
    case "$choice" in
        1) actions="publish read" ;;
        2) actions="read playback" ;;
        3) actions="publish read playback" ;;
        *) actions="publish read playback admin" ;;
    esac

    path="$(ask_value "Path scope for $who" "all" "a stream name such as cam, or \"all\"")"
    if [[ "$path" == "all" || -z "$path" ]]; then
        path=""
    elif [[ ! "$path" =~ ^[A-Za-z0-9._/-]+$ ]]; then
        # stderr: this function's stdout is the permission list it returns.
        log_warn "\"$path\" is not a usable path name; falling back to all paths." >&2
        path=""
    fi

    for act in $actions; do
        if [[ "$act" == "admin" ]]; then
            # api, metrics and pprof are server-wide; a path would mean nothing.
            out="${out}api|
metrics|
pprof|
"
        else
            out="${out}${act}|${path}
"
        fi
    done
    printf '%s' "$out"
}

ask_ips() {
    local who="$1" ips
    while true; do
        ips="$(ask_value "Source addresses allowed for $who" "any" \
                         "comma-separated IPs or CIDRs, or \"any\"")"
        if [[ "$ips" == "any" || -z "$ips" ]]; then
            printf ''
            return 0
        fi
        if [[ "$ips" =~ ^[0-9A-Fa-f:./,]+$ ]]; then
            printf '%s' "$ips"
            return 0
        fi
        # stderr, for the same reason as ask_username.
        log_warn "Use IPv4/IPv6 addresses or CIDRs separated by commas, or \"any\"." >&2
    done
}

collect_one_user() {
    local u p perms ips hash
    u="$(ask_username)"
    ask_password "$u"
    p="$PASSWORD_IN"; PASSWORD_IN=""
    perms="$(ask_role_perms "$u")"
    ips="$(ask_ips "$u")"

    log_step "Hashing the password for $u..."
    hash="$(hash_password "$p")"
    p=""
    log_ok "$u will be stored as argon2id."

    ENTRY_USER+=("$u")
    ENTRY_PASS+=("$hash")
    ENTRY_IPS+=("$ips")
    ENTRY_PERMS+=("$perms")
    ENTRY_ORIGIN+=("new")
    ADDED_THIS_RUN=$(( ADDED_THIS_RUN + 1 ))
}

collect_users() {
    while true; do
        collect_one_user
        ask_confirm "Add another user?" N || break
    done
    log_ok "$ADDED_THIS_RUN user(s) collected. Full list:"
    show_entries
}

# ‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒
#                                                      WRITING config/users.env
# ‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒

# cat over the destination rather than mv a temp onto it: mv would carry the
# temp file's 0600 mode and a new inode, and quietly break anything watching
# the path. The chmod that follows is deliberate, not inherited.
replace_file_contents() {
    local src="$1" dst="$2"
    cat "$src" > "$dst"
}

backup_users_file() {
    local stamp bak
    [[ -f "$USERS_FILE" ]] || return 0
    stamp="$(date +%Y%m%d-%H%M%S)"
    bak="$USERS_FILE.pre-mediamtx-users.$stamp.bak"
    cp "$USERS_FILE" "$bak"
    chmod 600 "$bak"
    log_ok "Backed up to $(basename "$bak")."
}

render_users_file() {
    local out="$1" i j n line act path
    n="${#ENTRY_USER[@]}"
    {
        cat <<'HEADER'
# MediaMTX internal-authentication users — generated by mediamtx-users.sh.
# Rerun that script to change this file; it shows the list below and asks
# before touching it. Hand edits survive, but nothing validates them.
#
# Every value is single-quoted on purpose. Compose interpolates unquoted
# env_file values, and an argon2 hash starts with `$argon2id`, which reads as
# a variable reference and expands to nothing.
#
# This file is inert until config/mediamtx.yml uncomments both
# `authMethod: internal` and `authInternalUsers: []`. The empty list is not
# optional: MediaMTX merges these variables into the built-in user list field
# by field rather than replacing it, so a permission you never granted can
# survive from the built-in entry at the same index.
HEADER
        printf '#\n# Written %s by %s.\n' "$(date +%Y-%m-%d\ %H:%M:%S)" "${USER:-$(id -un)}"

        for (( i = 0; i < n; i++ )); do
            printf '\n# ‒‒ user %d — %s — %s — from %s ‒‒\n' \
                "$i" "${ENTRY_USER[$i]}" \
                "$(perms_summary "${ENTRY_PERMS[$i]}")" \
                "${ENTRY_IPS[$i]:-any address}"
            printf "MTX_AUTHINTERNALUSERS_%d_USER='%s'\n" "$i" "${ENTRY_USER[$i]}"
            printf "MTX_AUTHINTERNALUSERS_%d_PASS='%s'\n" "$i" "${ENTRY_PASS[$i]}"
            printf "MTX_AUTHINTERNALUSERS_%d_IPS='%s'\n"  "$i" "${ENTRY_IPS[$i]}"
            j=0
            while IFS= read -r line; do
                [[ -z "$line" ]] && continue
                act="${line%%|*}"; path="${line#*|}"
                printf "MTX_AUTHINTERNALUSERS_%d_PERMISSIONS_%d_ACTION='%s'\n" "$i" "$j" "$act"
                case "$act" in
                    api|metrics|pprof) : ;;
                    *) printf "MTX_AUTHINTERNALUSERS_%d_PERMISSIONS_%d_PATH='%s'\n" "$i" "$j" "$path" ;;
                esac
                j=$(( j + 1 ))
            done <<< "${ENTRY_PERMS[$i]}"
        done

        cat <<TAIL

# ‒‒ managed tail entry — do not renumber ‒‒
# With authInternalUsers emptied in mediamtx.yml, the built-in localhost API
# user is gone too. This puts it back, so \`docker compose exec\`-style API
# calls and the metrics endpoint still answer on the Pi itself.
MTX_AUTHINTERNALUSERS_${n}_USER='any'
MTX_AUTHINTERNALUSERS_${n}_PASS=''
MTX_AUTHINTERNALUSERS_${n}_IPS='127.0.0.1,::1'
MTX_AUTHINTERNALUSERS_${n}_PERMISSIONS_0_ACTION='api'
MTX_AUTHINTERNALUSERS_${n}_PERMISSIONS_1_ACTION='metrics'
MTX_AUTHINTERNALUSERS_${n}_PERMISSIONS_2_ACTION='pprof'
TAIL
    } > "$out"
}

write_users_file() {
    local tmp dir
    dir="$(dirname "$USERS_FILE")"
    [[ -d "$dir" ]] || mkdir -p "$dir"
    backup_users_file
    tmp="$(mktemp "${TMPDIR:-/tmp}/mediamtx-users.XXXXXX")"
    chmod 600 "$tmp"
    render_users_file "$tmp"
    if [[ -f "$USERS_FILE" ]]; then
        replace_file_contents "$tmp" "$USERS_FILE"
    else
        cp "$tmp" "$USERS_FILE"
    fi
    rm -f "$tmp"
    chmod 600 "$USERS_FILE"
    WROTE_FILE=1
    if (( ! HAD_FILE )); then
        log_info "New file: $ADDED_THIS_RUN user(s) written."
    else
        case "$MODE" in
            append)    log_info "Append: $(( ${#ENTRY_USER[@]} - ADDED_THIS_RUN )) kept, $ADDED_THIS_RUN added." ;;
            overwrite) log_info "Overwrite: the previous list was replaced." ;;
        esac
    fi
    log_ok "Wrote ${#ENTRY_USER[@]} user(s) plus the localhost API entry to $USERS_FILE (mode 600)."
}

# ‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒
#                                                                 WIRING CHECKS
# ‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒

# The file only does something if two other files agree with it. Say so here
# rather than letting the user discover it as a stream that never asks for a
# password.
check_wiring() {
    local yml_ok=0 compose_ok=0
    if [[ -f "$MEDIAMTX_YML" ]] \
       && grep -qE '^[[:space:]]*authInternalUsers:[[:space:]]*\[\][[:space:]]*$' "$MEDIAMTX_YML"; then
        yml_ok=1
    fi
    if [[ -f "$COMPOSE_FILE" ]] && grep -q 'config/users.env' "$COMPOSE_FILE"; then
        compose_ok=1
    fi

    if (( yml_ok )); then
        log_ok "config/mediamtx.yml has authInternalUsers: [] uncommented — authentication is armed."
    else
        log_warn "config/mediamtx.yml still has authentication commented out; these users are inert."
    fi
    if (( compose_ok )); then
        log_ok "compose.yaml loads config/users.env."
    else
        log_warn "compose.yaml does not reference config/users.env; the container will never see these users."
    fi
}

# ‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒
#                                                                          MAIN
# ‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒

main() {
    parse_args "$@"
    banner "MEDIAMTX USER MANAGER" "internal auth · argon2id"

    check_for_root
    require_interactive

    log_phase "PREFLIGHT"
    detect_package_manager
    ensure_argon2
    log_info "Users file: $USERS_FILE"

    log_phase "EXISTING USERS"
    if ! review_existing; then
        log_ok "Nothing changed. $USERS_FILE is as you left it."
        log_complete "NO CHANGES WRITTEN"
        echo
        return 0
    fi

    log_phase "NEW USERS"
    collect_users

    if (( ADDED_THIS_RUN == 0 )); then
        log_warn "No users were added, so the file was not rewritten."
        log_complete "NO CHANGES WRITTEN"
        echo
        return 0
    fi

    log_phase "WRITE"
    write_users_file

    log_phase "WIRING"
    check_wiring

    log_complete "USERS WRITTEN"
    log_next "Uncomment authMethod and authInternalUsers in config/mediamtx.yml."
    log_next "Restart the stack:  docker compose up -d"
    log_next "Test:  ffplay rtsp://<user>:<password>@<pi>:8554/cam"
    log_next "users.env holds password hashes at mode 600 — keep it out of git."
    echo
}

main "$@"
