#!/usr/bin/env bash
#
# frigate-setup.sh
#
# Preflight and first run for the Frigate stack. Everything it checks is
# something that otherwise fails late, quietly, or as a symptom that points
# somewhere other than the cause: a detector overlay that disagrees with
# config.yml, a device node the host does not have, recordings aimed at an SD
# card, a JWT secret that changes on every restart.
#
# Usage:  ./frigate-setup.sh [-c|--check] [-y|--yes] [-h|--help]
#
#   -c, --check   Run every check and stop. Touches nothing, starts nothing.
#   -y, --yes     Take the default at every prompt. For unattended rebuilds.
#
# Do not run as root. It uses sudo per step and refuses an EUID of 0.
# It is idempotent — rerun it as often as you like.
#
# On a first run it will hand you the generated admin password. That password
# is in the container log, and on 0.17.2 any authenticated user can read the
# container log. Change it at Settings > Users before you create a second
# account. The README says this again, at more length, and means it.
# ‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒

set -eo pipefail

# ‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒
#                                                                       GLOBALS
# ‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$SCRIPT_DIR/.env"
ENV_EXAMPLE="$SCRIPT_DIR/.env.example"
CONFIG_FILE="$SCRIPT_DIR/config/config.yml"
CONFIG_EXAMPLE="$SCRIPT_DIR/config/config.yml.example"
WG_CONF="$SCRIPT_DIR/wireguard/wg0.conf"

CHECK_ONLY=0
FAILURES=0            # hard problems; the stack does not start
WARNINGS=0            # things that work today and bite later

DC=()                 # the docker compose invocation, as an array

# ‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒
#                                PRETTY OUTPUT — IT DOJO TERMINAL DESIGN SYSTEM
# ‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒
# Copied verbatim from ~/projects/qol/linux/base_functions.sh, the canonical
# block, because that library is Linux-only and this script also runs on macOS.
# Copy it whole or not at all — a partial copy is a restyle. Palette and rules:
#   ~/vaults/dojobrain/30-references/design-system/itdojo-terminal-design-system.md
# Decide color and depth once. Re-callable so tests can force a tier.
#   NO_COLOR         — set to disable color entirely (wins over everything)
#   QOL_FORCE_COLOR  — set to keep color when stdout is not a TTY (e.g. less -R)
#   QOL_COLOR_DEPTH  — truecolor (default) | 256 | 8 | none
# Several inks have no reader in any one script that carries this block —
# a token ink with no consumer is suppressed, not deleted, because dropping a
# color from a palette copy makes it a worse copy.
# shellcheck disable=SC2034
qol_init_color() {
    if [[ -n "${NO_COLOR:-}" ]]; then
        QOL_COLOR=""
    elif [[ -n "${QOL_FORCE_COLOR:-}" || -t 1 ]]; then
        QOL_COLOR=1
    else
        QOL_COLOR=""
    fi

    case "${QOL_COLOR_DEPTH:-truecolor}" in
        256)  QOL_DEPTH=256 ;;
        8)    QOL_DEPTH=8 ;;
        none) QOL_DEPTH=none ;;
        *)    QOL_DEPTH=truecolor ;;
    esac
    [[ -z "$QOL_COLOR" ]] && QOL_DEPTH=none

# ‒‒ generated by dojobrain scripts/build-design-tokens.py --emit-bash
# ‒‒ do not hand-edit; edit tokens/colors.css and re-emit.
    case "$QOL_DEPTH" in
        truecolor)
            QOL_STEP=$'\033[38;2;188;176;232m'
            QOL_PASS=$'\033[38;2;78;206;106m'
            QOL_INFO=$'\033[38;2;122;160;216m'
            QOL_WARN=$'\033[38;2;224;180;90m'
            QOL_STOP=$'\033[38;2;224;107;130m'
            QOL_FG=$'\033[38;2;228;222;245m'
            QOL_META=$'\033[38;2;154;147;181m'
            QOL_RULE=$'\033[38;2;74;65;112m'
            QOL_SEL=$'\033[48;2;36;29;61m'
            QOL_OKBG=$'\033[48;2;21;50;31m'
            ;;
        256)
            QOL_STEP=$'\033[38;5;140m'
            QOL_PASS=$'\033[38;5;77m'
            QOL_INFO=$'\033[38;5;110m'
            QOL_WARN=$'\033[38;5;179m'
            QOL_STOP=$'\033[38;5;168m'
            QOL_FG=$'\033[38;5;189m'
            QOL_META=$'\033[38;5;103m'
            QOL_RULE=$'\033[38;5;60m'
            QOL_SEL=$'\033[48;5;235m'
            QOL_OKBG=$'\033[48;5;22m'
            ;;
        8)
            QOL_STEP=$'\033[94m'
            QOL_PASS=$'\033[92m'
            QOL_INFO=$'\033[94m'
            QOL_WARN=$'\033[93m'
            QOL_STOP=$'\033[91m'
            QOL_FG=$'\033[97m'
            QOL_META=$'\033[90m'
            QOL_RULE=$'\033[90m'
            QOL_SEL=$'\033[7m'
            QOL_OKBG=$'\033[7m'
            ;;
        *)
            QOL_STEP="" QOL_PASS="" QOL_INFO="" QOL_WARN="" QOL_STOP="" QOL_FG="" QOL_META="" QOL_RULE="" QOL_SEL="" QOL_OKBG=""
            ;;
    esac
# ‒‒ end generated block

    if [[ "$QOL_DEPTH" == "none" ]]; then
        QOL_BOLD="" QOL_DIM="" QOL_RESET=""
    else
        QOL_BOLD=$'\033[1m'; QOL_DIM=$'\033[2m'; QOL_RESET=$'\033[0m'
    fi
}
qol_init_color

# Terminal width, falling back to 80 with no TTY (cron, CI, pipes).
#
# Ask the terminal, not terminfo. `tput cols 2>/dev/null` inside a command
# substitution answers 80 however wide the window is: with stdout captured,
# ncurses reads the window size off stderr instead, and that redirect throws
# the only usable fd away. Every rule, bookend and selection bar in this file
# was pinned to 80 columns by it. stty asks /dev/tty directly, so no amount of
# nesting can hide the answer. COLUMNS still wins when set, as an override.
_term_cols() {
    local cols="${COLUMNS:-}"
    if [[ ! "$cols" =~ ^[0-9]+$ ]] || (( cols <= 0 )); then
        cols="$(stty size </dev/tty 2>/dev/null | cut -d' ' -f2)"
    fi
    if [[ ! "$cols" =~ ^[0-9]+$ ]] || (( cols <= 0 )); then
        cols=80
    fi
    printf '%s' "$cols"
}

# Repeat a character n times. Emits nothing for n <= 0.
_repeat() {
    local ch="$1" n="$2" line
    [[ "$n" =~ ^-?[0-9]+$ ]] || return 0
    (( n <= 0 )) && return 0
    printf -v line '%*s' "$n" ''
    printf '%s' "${line// /$ch}"
}

# One milestone line. The prefix is exactly 9 columns: gutter, space,
# 4-char badge, 3 spaces. Message text therefore starts at column 10.
_log_line() {
    local ink="$1" badge="$2" text="$3"
    printf '%s%s▌ %-4s   %s%s\n' "$QOL_BOLD" "$ink" "$badge" "$text" "$QOL_RESET"
}

log_step() { _log_line "$QOL_STEP" STEP "$1"; }
log_ok()   { _log_line "$QOL_PASS" PASS "$1"; }
log_info() { _log_line "$QOL_INFO" INFO "$1"; }
log_warn() { _log_line "$QOL_WARN" WARN "$1"; }
log_err()  { _log_line "$QOL_STOP" STOP "$1" >&2; }
log_ask()  { _log_line "$QOL_STEP" ASK  "$1"; }
log_next() { _log_line "$QOL_INFO" NEXT "$1"; }

# Phase boundary: a gray rule carrying the phase name in violet. A rule now
# means "new phase", which is information; a rule per line meant nothing.
log_phase() {
    local title="$1" cols fill
    cols="$(_term_cols)"
    fill=$(( cols - ${#title} - 4 ))
    printf '\n%s──%s %s%s%s%s %s%s\n\n' \
        "$QOL_RULE" "$QOL_RESET" \
        "$QOL_BOLD$QOL_STEP" "$title" "$QOL_RESET" \
        "$QOL_RULE" "$(_repeat '─' "$fill")" "$QOL_RESET"
}

# Run bookends. Jade rules, so a run's edges are findable when scrolling
# back through screens of package-manager output; phase rules are gray.
banner() {
    local title="$1" sub="${2:-}" cols
    cols="$(_term_cols)"
    printf '%s%s%s\n' "$QOL_PASS" "$(_repeat '━' "$cols")" "$QOL_RESET"
    printf '  %s%s⛩ %s ⛩%s' "$QOL_BOLD" "$QOL_PASS" "$title" "$QOL_RESET"
    [[ -n "$sub" ]] && printf '   %s%s%s' "$QOL_META" "$sub" "$QOL_RESET"
    printf '\n%s%s%s\n' "$QOL_PASS" "$(_repeat '━' "$cols")" "$QOL_RESET"
}

# NOTE: not named `complete` — that is a bash builtin.
log_complete() {
    local title="$1" cols
    cols="$(_term_cols)"
    printf '\n%s%s%s\n' "$QOL_PASS" "$(_repeat '━' "$cols")" "$QOL_RESET"
    printf '  %s%s%s ⛩ %s ⛩ %s\n' "$QOL_OKBG" "$QOL_BOLD" "$QOL_PASS" "$title" "$QOL_RESET"
    printf '%s%s%s\n\n' "$QOL_PASS" "$(_repeat '━' "$cols")" "$QOL_RESET"
}

# ‒‒ Back-compat ‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒
# Eight other scripts call these. Kept working, not kept identical: printline
# no longer appears in any log_* line, because the design uses phase rules.

# Print a separator line the width of the terminal.
# Usage: printline [solid|bullet|ibeam|star|plus|diamond|dentistry]
printline() {
    local sep
    case "${1:-solid}" in
        bullet)    sep="•" ;;
        ibeam)     sep="⌶" ;;
        star)      sep="★" ;;
        plus)      sep="✛" ;;
        diamond)   sep="◆" ;;
        dentistry) sep="⏥" ;;
        *)         sep="─" ;;
    esac
    printf '%s%s%s\n' "$QOL_RULE" "$(_repeat "$sep" "$(_term_cols)")" "$QOL_RESET"
}

# Print styled text with no separator. Also usable inline via command
# substitution: echo "I am a $(style_text "Raspberry Pi" bold wine)."
# Usage: style_text "text" [normal|bold|light] [brand or legacy color name]
# Brand names:  violet jade steel saffron wine prose meta rule
# Legacy names: blue   green  —     yellow  red   —     —    —
style_text() {
    local text="$1" weight="${2:-normal}" color="${3:-}"
    local wt="" ink=""
    case "$weight" in
        bold)  wt="$QOL_BOLD" ;;
        light) wt="$QOL_DIM" ;;
    esac
    case "$color" in
        violet)        ink="$QOL_STEP" ;;
        jade|green)    ink="$QOL_PASS" ;;
        steel|blue)    ink="$QOL_INFO" ;;
        saffron|yellow) ink="$QOL_WARN" ;;
        wine|red)      ink="$QOL_STOP" ;;
        prose)         ink="$QOL_FG" ;;
        meta)          ink="$QOL_META" ;;
        rule)          ink="$QOL_RULE" ;;
    esac
    if [[ -z "$QOL_COLOR" ]] || [[ -z "$ink" && -z "$wt" ]]; then
        printf '%s\n' "$text"
        return 0
    fi
    printf '%s%s%s%s\n' "$wt" "$ink" "$text" "$QOL_RESET"
}

# Separator + styled text. Retained for callers that predate log_phase;
# new code should use log_phase or a log_* helper instead.
format_font() {
    printline
    style_text "$1" "${2:-bold}" "${3:-saffron}"
}

# Banner for script titles. Prefer banner/log_complete in new code.
log_title() {
    local cols
    cols="$(_term_cols)"
    printf '%s%s%s\n' "$QOL_PASS" "$(_repeat '━' "$cols")" "$QOL_RESET"
    style_text "$1" bold jade
    printf '%s%s%s\n' "$QOL_PASS" "$(_repeat '━' "$cols")" "$QOL_RESET"
}

# ‒‒ Interactive ‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒
# Three question shapes, sharing gotime's chrome. Prompts go to stderr so
# ask_value and ask_choice can be captured with $(...). All three skip the
# prompt and return the default when ASSUME_YES is set or stdin is not a
# TTY — the priority order install_nano.sh already follows.

# Decode one keypress into _KEY (and _KEYCH for digits). Bash 3.2 safe:
# no read -N, no fractional -t. Arrows arrive as ESC then "[A"/"OA".
_read_key() {
    local k s
    _KEY=""; _KEYCH=""
    IFS= read -rsn1 k || { _KEY="QUIT"; return 0; }
    if [[ -z "$k" ]]; then _KEY="ENTER"; return 0; fi
    case "$k" in
        $'\r'|$'\n') _KEY="ENTER" ;;
        $'\x1b')
            s=""
            IFS= read -rsn2 -t 1 s
            case "$s" in
                '[A'|'OA') _KEY="UP" ;;
                '[B'|'OB') _KEY="DOWN" ;;
                '')        _KEY="QUIT" ;;
                *)         _KEY="OTHER" ;;
            esac ;;
        [0-9]) _KEY="DIGIT"; _KEYCH="$k" ;;
        k|K)   _KEY="UP" ;;
        j|J)   _KEY="DOWN" ;;
        q|Q)   _KEY="QUIT" ;;
        *)     _KEY="OTHER" ;;
    esac
    return 0
}

# ask_confirm "question" [Y|N]  ->  exit 0 for yes, 1 for no
ask_confirm() {
    local q="$1" def="${2:-N}" hint reply
    if [[ -n "${ASSUME_YES:-}" ]]; then return 0; fi
    if [[ ! -t 0 ]]; then [[ "$def" == "Y" ]]; return $?; fi
    if [[ "$def" == "Y" ]]; then hint="Y/n"; else hint="y/N"; fi
    _log_line "$QOL_STEP" ASK "$q" >&2
    printf '    %s❯%s %s[%s]%s ' "$QOL_PASS" "$QOL_RESET" "$QOL_META" "$hint" "$QOL_RESET" >&2
    read -r reply
    reply="${reply:-$def}"
    case "$reply" in [Yy]*) return 0 ;; *) return 1 ;; esac
}

# ask_value "question" "default" ["hint"]  ->  echoes the answer
ask_value() {
    local q="$1" def="$2" hint="${3:-}" reply
    if [[ -n "${ASSUME_YES:-}" || ! -t 0 ]]; then printf '%s' "$def"; return 0; fi
    _log_line "$QOL_STEP" ASK "$q" >&2
    [[ -n "$hint" ]] && printf '         %s%s%s\n' "$QOL_META" "$hint" "$QOL_RESET" >&2
    printf '    %s❯%s [%s%s%s] ' "$QOL_PASS" "$QOL_RESET" "$QOL_PASS" "$def" "$QOL_RESET" >&2
    read -r reply
    printf '%s' "${reply:-$def}"
}

# Draw the choice list. Emits exactly (count + 3) lines so the caller knows

# ‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒
#                                                                       PLUMBING
# ‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒

usage() {
    sed -n '3,20p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'
}

parse_args() {
    while (( $# )); do
        case "$1" in
            -c|--check) CHECK_ONLY=1 ;;
            -y|--yes)   ASSUME_YES=1 ;;
            -h|--help)  usage; exit 0 ;;
            *)          log_err "Unknown argument: $1"; usage; exit 2 ;;
        esac
        shift
    done
}

check_for_root() {
    if (( EUID == 0 )); then
        log_err "Do not run this as root. It calls sudo where it needs to."
        exit 1
    fi
}

fail()  { log_err  "$1"; FAILURES=$(( FAILURES + 1 )); }
warn()  { log_warn "$1"; WARNINGS=$(( WARNINGS + 1 )); }

# Read one key out of .env without sourcing it. Sourcing would execute
# whatever is in there and would also mangle values holding `$`.
env_get() {
    local key="$1" line
    [[ -f "$ENV_FILE" ]] || return 0
    line="$(grep -E "^[[:space:]]*${key}=" "$ENV_FILE" | tail -n1 || true)"
    [[ -z "$line" ]] && return 0
    line="${line#*=}"
    line="${line%\"}"; line="${line#\"}"
    line="${line%\'}"; line="${line#\'}"
    printf '%s' "$line"
}

# Rewrite one key in .env through a temp file. `sed -i` needs a different
# argument on macOS than on Linux, and this script should not care which it
# is running on.
env_set() {
    local key="$1" value="$2" tmp
    tmp="$(mktemp "${ENV_FILE}.XXXXXX")"
    awk -v k="$key" -v v="$value" '
        $0 ~ "^[[:space:]]*" k "=" { print k "=" v; found = 1; next }
        { print }
        END { if (!found) print k "=" v }
    ' "$ENV_FILE" > "$tmp"
    cat "$tmp" > "$ENV_FILE"
    rm -f "$tmp"
}

# ‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒
#                                                                 HOST & DOCKER
# ‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒

# Best-effort host identification, used only to make the advice specific.
host_model() {
    if [[ -r /proc/device-tree/model ]]; then
        tr -d '\0' < /proc/device-tree/model
    elif [[ -r /sys/devices/virtual/dmi/id/product_name ]]; then
        cat /sys/devices/virtual/dmi/id/product_name
    else
        uname -m
    fi
}

check_docker() {
    log_step "Checking Docker..."

    if ! command -v docker >/dev/null 2>&1; then
        fail "docker is not installed or not on PATH."
        return
    fi

    if ! docker info >/dev/null 2>&1; then
        fail "Cannot talk to the Docker daemon. Is it running, and are you in the docker group?"
        return
    fi

    if docker compose version >/dev/null 2>&1; then
        DC=(docker compose)
    elif command -v docker-compose >/dev/null 2>&1; then
        DC=(docker-compose)
        warn "Using legacy docker-compose. This stack expects the Compose v2 plugin."
    else
        fail "Docker Compose is not available. Install the docker-compose-plugin package."
        return
    fi

    log_ok "Docker is up: $(docker --version | cut -d, -f1), $("${DC[@]}" version --short 2>/dev/null || echo unknown)."
}

# ‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒
#                                                                    THE TWO FILES
# ‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒

# On a fresh copy of this folder, seed .env and config.yml from the examples
# and stop. Both need decisions the script cannot make.
seed_if_missing() {
    local seeded=0

    if [[ ! -f "$ENV_FILE" ]]; then
        cp "$ENV_EXAMPLE" "$ENV_FILE"
        log_ok "Created .env from .env.example."
        seeded=1
    fi

    if [[ ! -f "$CONFIG_FILE" ]]; then
        cp "$CONFIG_EXAMPLE" "$CONFIG_FILE"
        log_ok "Created config/config.yml from config.yml.example."
        seeded=1
    fi

    if (( seeded )); then
        log_phase "EDIT THESE, THEN RUN AGAIN"
        log_next "\$EDITOR $ENV_FILE"
        log_next "   COMPOSE_FILE, FRIGATE_IMAGE, FRIGATE_MEDIA, TZ, RTSP credentials"
        log_next "\$EDITOR $CONFIG_FILE"
        log_next "   the detector block matching COMPOSE_FILE, then your cameras"
        log_next "./frigate-setup.sh"
        exit 0
    fi
}

# ‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒
#                                                             PROFILE COHERENCE
# ‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒
# The one thing nothing else catches: COMPOSE_FILE and config.yml each name a
# detector, independently, and a mismatch starts cleanly and then detects
# nothing. This is the check the whole script exists for.

DETECTOR=""           # openvino | coral-usb | hailo | rpi | cpu
NETWORK=""            # ports | wireguard

check_profile() {
    log_step "Checking profile selection..."

    local cf; cf="$(env_get COMPOSE_FILE)"
    if [[ -z "$cf" ]]; then
        fail "COMPOSE_FILE is not set in .env. Nothing selects a detector or a network overlay."
        return
    fi

    [[ "$cf" == *compose.yaml* ]] || fail "COMPOSE_FILE does not include the base compose.yaml."

    # Exactly one network overlay.
    local n=0
    [[ "$cf" == *compose.ports.yaml* ]]     && { NETWORK=ports;     n=$(( n + 1 )); }
    [[ "$cf" == *compose.wireguard.yaml* ]] && { NETWORK=wireguard; n=$(( n + 1 )); }
    if (( n == 0 )); then
        fail "COMPOSE_FILE names no network overlay. Add compose.ports.yaml or compose.wireguard.yaml."
    elif (( n > 1 )); then
        fail "COMPOSE_FILE names both network overlays. Frigate cannot publish ports and join a namespace."
    fi

    # Exactly one detector overlay.
    local d=0
    [[ "$cf" == *compose.openvino.yaml* ]]  && { DETECTOR=openvino;  d=$(( d + 1 )); }
    [[ "$cf" == *compose.coral-usb.yaml* ]] && { DETECTOR=coral-usb; d=$(( d + 1 )); }
    [[ "$cf" == *compose.hailo.yaml* ]]     && { DETECTOR=hailo;     d=$(( d + 1 )); }
    [[ "$cf" == *compose.rpi.yaml* ]]       && { DETECTOR=rpi;       d=$(( d + 1 )); }
    [[ "$cf" == *compose.cpu.yaml* ]]       && { DETECTOR=cpu;       d=$(( d + 1 )); }
    if (( d == 0 )); then
        fail "COMPOSE_FILE names no detector overlay."
    elif (( d > 1 )); then
        fail "COMPOSE_FILE names $d detector overlays. Pick one."
    fi

    (( FAILURES )) && return
    log_ok "Profile: $DETECTOR detection, $NETWORK networking."
}

# What config.yml actually asks for, reading only uncommented lines.
config_detector() {
    grep -E '^[[:space:]]+type:[[:space:]]*(openvino|edgetpu|hailo8l|cpu)[[:space:]]*$' \
        "$CONFIG_FILE" 2>/dev/null | awk '{print $2}' | sort -u
}

check_detector_agreement() {
    [[ -n "$DETECTOR" ]] || return 0
    log_step "Checking that config.yml agrees with the overlay..."

    local want found
    case "$DETECTOR" in
        openvino)  want=openvino ;;
        coral-usb) want=edgetpu ;;
        hailo)     want=hailo8l ;;
        rpi|cpu)   want=cpu ;;
    esac

    found="$(config_detector | tr '\n' ' ' | sed 's/ $//')"

    if [[ -z "$found" ]]; then
        fail "config.yml has no uncommented detector block. Uncomment the $want one."
    elif [[ "$found" != "$want" ]]; then
        fail "Mismatch: COMPOSE_FILE selects '$DETECTOR' (type: $want), config.yml declares 'type: $found'."
        log_next "Frigate would start, load the wrong detector, and detect nothing on hardware it cannot open."
    else
        log_ok "config.yml declares 'type: $want', which matches the overlay."
    fi
}

# ‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒
#                                                                       DEVICES
# ‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒
# Compose refuses to start a service whose `devices:` path does not exist, and
# the error names the path without saying which overlay asked for it.

check_devices() {
    [[ -n "$DETECTOR" ]] || return 0
    log_step "Checking device nodes for the $DETECTOR profile..."

    case "$DETECTOR" in
        openvino)
            if [[ -e /dev/dri/renderD128 ]]; then
                log_ok "/dev/dri/renderD128 is present."
            else
                fail "/dev/dri/renderD128 does not exist. No Intel render node on this host."
                log_next "ls -l /dev/dri/   — a second GPU may put it at renderD129; edit compose.openvino.yaml."
                log_next "On a Raspberry Pi or Gateworks board there is no Intel GPU. Use coral-usb, hailo, rpi or cpu."
            fi
            local rgid; rgid="$(env_get RENDER_GID)"
            local real; real="$(getent group render 2>/dev/null | cut -d: -f3 || true)"
            if [[ -n "$real" && -n "$rgid" && "$real" != "$rgid" ]]; then
                warn "RENDER_GID is $rgid but this host's render group is $real. Frigate will get EACCES on the render node."
            fi
            ;;
        coral-usb)
            if [[ -d /dev/bus/usb ]]; then
                log_ok "/dev/bus/usb is present."
            else
                fail "/dev/bus/usb does not exist. No USB subsystem to hand the container."
            fi
            if command -v lsusb >/dev/null 2>&1; then
                if lsusb 2>/dev/null | grep -qiE '18d1:9302|1a6e:089a|Global Unichip|Google Inc'; then
                    log_ok "A Coral accelerator is on the bus."
                else
                    warn "No Coral found by lsusb. It enumerates as 1a6e:089a cold and 18d1:9302 after firmware upload."
                fi
            fi
            ;;
        hailo)
            if [[ -e /dev/hailo0 ]]; then
                log_ok "/dev/hailo0 is present."
            else
                fail "/dev/hailo0 does not exist. The Hailo driver is not loaded."
                log_next "sudo apt install hailo-all && sudo reboot"
                log_next "The Raspberry Pi AI Camera (IMX500) is not this device. Only the M.2 Hailo module works."
            fi
            ;;
        rpi)
            if [[ -e /dev/video11 ]]; then
                log_ok "/dev/video11 is present."
            else
                fail "/dev/video11 does not exist."
                log_next "A Raspberry Pi 5 has no hardware H.264 decoder and never exposes it. Use compose.cpu.yaml there."
            fi
            ;;
        cpu)
            log_ok "No devices needed."
            ;;
    esac
}

# ‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒
#                                                                       STORAGE
# ‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒

check_storage() {
    log_step "Checking recording storage..."

    local media; media="$(env_get FRIGATE_MEDIA)"
    if [[ -z "$media" ]]; then
        fail "FRIGATE_MEDIA is not set in .env."
        return
    fi

    if [[ ! -d "$media" ]]; then
        fail "FRIGATE_MEDIA points at $media, which is not a directory."
        log_next "sudo mkdir -p $media && sudo chown -R \$(id -u):\$(id -g) $media"
        return
    fi

    if [[ ! -w "$media" ]]; then
        fail "$media is not writable by $(id -un). Frigate records as UID $(id -u)."
        log_next "sudo chown -R \$(id -u):\$(id -g) $media"
        return
    fi

    local mp free
    mp="$(df -P "$media" 2>/dev/null | tail -n1 | awk '{print $6}')"
    free="$(df -Ph "$media" 2>/dev/null | tail -n1 | awk '{print $4}')"
    log_ok "$media is writable — mount point $mp, $free free."

    # The SD-card case. On a Pi this is not a stylistic preference.
    if [[ "$mp" == "/" ]]; then
        local model; model="$(host_model)"
        if [[ "$model" == *"Raspberry Pi"* ]]; then
            warn "Recordings are on the root filesystem of a $model — almost certainly the SD card."
            log_next "Continuous recording will wear an SD card out in months. Point FRIGATE_MEDIA at a USB SSD."
        else
            warn "Recordings are on the root filesystem. Fine if that is real storage; check it is not eMMC or an SD card."
        fi
    fi

    # Free space against the retention actually configured.
    local cont; cont="$(grep -A2 -E '^[[:space:]]*continuous:' "$CONFIG_FILE" 2>/dev/null \
        | grep -E '^[[:space:]]*days:' | head -n1 | awk '{print $2}' || true)"
    local cams; cams="$(awk '/^cameras:/{f=1;next} /^[a-z]/{f=0} f && /^  [a-z_]+:/{c++} END{print c+0}' "$CONFIG_FILE" 2>/dev/null || echo 0)"
    if [[ "$cont" =~ ^[0-9]+$ ]] && (( cont > 0 )) && (( cams > 0 )); then
        local need=$(( cont * cams * 21 ))
        log_info "Continuous retention is ${cont}d across ${cams} camera(s): roughly ${need} GB at 2 MB/s each."
    fi
}

# ‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒
#                                                                       SECRETS
# ‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒

check_jwt_secret() {
    log_step "Checking the session signing secret..."

    local secret; secret="$(env_get FRIGATE_JWT_SECRET)"

    if [[ -n "$secret" ]]; then
        if (( ${#secret} < 64 )); then
            fail "FRIGATE_JWT_SECRET is ${#secret} characters. Frigate requires at least 64."
        else
            log_ok "FRIGATE_JWT_SECRET is set (${#secret} characters)."
        fi
        return
    fi

    if (( CHECK_ONLY )); then
        warn "FRIGATE_JWT_SECRET is empty. Frigate would mint a new one each start and log everyone out."
        return
    fi

    if ! command -v openssl >/dev/null 2>&1; then
        warn "FRIGATE_JWT_SECRET is empty and openssl is not installed. Set it by hand: 64+ characters."
        return
    fi

    secret="$(openssl rand -hex 32)"
    env_set FRIGATE_JWT_SECRET "$secret"
    log_ok "Generated FRIGATE_JWT_SECRET and wrote it to .env. Sessions now survive restarts."
}

# ‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒
#                                                                     WIREGUARD
# ‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒

# IPv4 dotted quad -> integer. Returns 1 on anything that is not one, so
# callers can skip IPv6 and malformed entries rather than comparing garbage.
_ip2int() {
    local a b c d IFS=.
    [[ "$1" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]] || return 1
    read -r a b c d <<<"$1"
    (( a < 256 && b < 256 && c < 256 && d < 256 )) || return 1
    printf '%s' $(( (a << 24) | (b << 16) | (c << 8) | d ))
}

# Do two CIDRs cover any address in common? Mask both to the SHORTER prefix and
# compare: if the networks match there, one contains the other. Returns 0 on
# overlap.
_cidr_overlap() {
    local a="${1%%/*}" la="${1##*/}" b="${2%%/*}" lb="${2##*/}" ai bi m sh
    [[ "$la" =~ ^[0-9]+$ ]] && (( la <= 32 )) || la=32
    [[ "$lb" =~ ^[0-9]+$ ]] && (( lb <= 32 )) || lb=32
    ai="$(_ip2int "$a")" || return 1
    bi="$(_ip2int "$b")" || return 1
    m=$(( la < lb ? la : lb ))
    (( m == 0 )) && return 0
    sh=$(( 32 - m ))
    (( (ai >> sh) == (bi >> sh) ))
}

# Every IPv4 network this host can already reach directly: real NICs, docker0,
# every br-* bridge, plus the subnets of Docker networks that have no live
# bridge yet. Tunnel interfaces are excluded — those are the far side.
#
# Every source is individually tolerated. Under `set -e` with pipefail a
# missing `ip` used to abort the whole function, which left the caller
# comparing against an empty list and reporting "no overlap" — a check that
# passes because it did not run. The caller now counts what it got.
_local_subnets() {
    local nets addr mask bits m

    if command -v ip >/dev/null 2>&1; then
        ip -o -f inet addr show 2>/dev/null \
            | awk '$2 !~ /^(lo|wg|tun|tap)/ {print $4}' || true
    elif command -v ifconfig >/dev/null 2>&1; then
        # BSD/macOS, for authoring. Deployment hosts have `ip`. ifconfig
        # reports a hex netmask, so turn it into a prefix length by counting
        # bits.
        while read -r addr mask; do
            [[ "$addr" =~ ^[0-9] ]] || continue
            [[ "$mask" == 0x* ]] || continue
            m=$(( mask )); bits=0
            while (( m > 0 )); do bits=$(( bits + (m & 1) )); m=$(( m >> 1 )); done
            printf '%s/%s\n' "$addr" "$bits"
        done < <(ifconfig 2>/dev/null | awk '/inet /{print $2, $4}') || true
    fi

    nets="$(docker network ls -q 2>/dev/null || true)"
    [[ -z "$nets" ]] && return 0
    # shellcheck disable=SC2086
    docker network inspect $nets \
        --format '{{range .IPAM.Config}}{{.Subnet}}{{"\n"}}{{end}}' 2>/dev/null || true
    return 0
}

# The mixed-ingest failure mode: a prefix in AllowedIPs that also covers
# something local silently captures it. The far-end LAN sharing a private
# range with the near-end LAN is the common case, and the symptom — local
# cameras dropping the moment the tunnel comes up — points nowhere near
# wg0.conf. Docker's own bridge pool is the same hazard for the broker.
check_allowedips_overlap() {
    local line allowed=() prefix local_net hits=0 compared=0

    line="$(grep -E '^[[:space:]]*AllowedIPs[[:space:]]*=' "$WG_CONF" | tail -n1 || true)"
    [[ -z "$line" ]] && { warn "wg0.conf has no AllowedIPs line. The tunnel will route nothing."; return; }

    # shellcheck disable=SC2206
    allowed=( ${line#*=} )
    allowed=( "${allowed[@]//,/}" )

    while IFS= read -r local_net; do
        [[ -z "$local_net" || "$local_net" == *:* ]] && continue
        compared=$(( compared + 1 ))
        for prefix in "${allowed[@]}"; do
            [[ -z "$prefix" || "$prefix" == *:* ]] && continue
            if _cidr_overlap "$prefix" "$local_net"; then
                fail "AllowedIPs $prefix overlaps this host's own network $local_net."
                hits=$(( hits + 1 ))
            fi
        done
    done < <(_local_subnets | sort -u)

    if (( hits )); then
        log_next "That prefix captures local traffic into the tunnel. LAN cameras, or mosquitto, stop answering."
        log_next "Fix on the far end: renumber that network, or narrow AllowedIPs to the camera addresses."
    elif (( compared == 0 )); then
        # Never report a pass we did not earn.
        warn "Could not enumerate this host's networks; the AllowedIPs overlap check did not run."
        log_next "Install iproute2, or compare AllowedIPs against 'ip addr' and your Docker subnets by hand."
    else
        log_ok "AllowedIPs does not overlap any of $compared local network(s)."
    fi
}

check_wireguard() {
    [[ "$NETWORK" == "wireguard" ]] || return 0
    log_step "Checking the WireGuard sidecar..."

    if [[ ! -f "$WG_CONF" ]]; then
        if (( CHECK_ONLY )); then
            fail "compose.wireguard.yaml is selected but wireguard/wg0.conf does not exist."
            log_next "cp wireguard/wg0.conf.example wireguard/wg0.conf && \$EDITOR wireguard/wg0.conf"
            return
        fi
        cp "$SCRIPT_DIR/wireguard/wg0.conf.example" "$WG_CONF"
        chmod 600 "$WG_CONF"
        fail "Created wireguard/wg0.conf from the example. It is a template, not a working tunnel."
        log_next "\$EDITOR $WG_CONF   — keys, Endpoint, and AllowedIPs"
        log_next "A host with no remote cameras wants compose.ports.yaml in COMPOSE_FILE instead."
        return
    fi

    if grep -q 'REPLACE_WITH' "$WG_CONF"; then
        fail "wireguard/wg0.conf still contains REPLACE_WITH placeholders."
        return
    fi

    local mode; mode="$(stat -c '%a' "$WG_CONF" 2>/dev/null || stat -f '%Lp' "$WG_CONF" 2>/dev/null || echo '')"
    if [[ -n "$mode" && "$mode" != "600" ]]; then
        warn "wireguard/wg0.conf is mode $mode. It holds a private key."
        log_next "chmod 600 $WG_CONF"
    fi

    if [[ -e /dev/net/tun ]]; then
        log_ok "/dev/net/tun is present."
    else
        fail "/dev/net/tun does not exist. sudo modprobe tun, and make it persistent."
    fi

    if modinfo wireguard >/dev/null 2>&1 || [[ -d /sys/module/wireguard ]]; then
        log_ok "The host kernel has WireGuard."
    else
        warn "No WireGuard kernel module found. The sidecar falls back to userspace, which costs CPU."
        log_next "That cost lands on the same cores already decoding video. Check before blaming the detector."
    fi

    # The routing trap, checked rather than only documented.
    if grep -qE '^[[:space:]]*AllowedIPs[[:space:]]*=.*0\.0\.0\.0/0' "$WG_CONF"; then
        warn "AllowedIPs includes 0.0.0.0/0 — a full tunnel inside the container's namespace."
        log_next "LAN cameras, the mosquitto service and replies to LAN browsers all route into the tunnel."
        log_next "Split-tunnel to the camera subnets, or add PostUp rules carving the Docker subnet back out."
    else
        check_allowedips_overlap
    fi

    if grep -qE '^[[:space:]]*DNS[[:space:]]*=' "$WG_CONF"; then
        warn "DNS is set in wg0.conf. It rewrites resolv.conf for the whole namespace."
        log_next "Frigate then cannot resolve 'mosquitto' and reports an MQTT failure that looks unrelated."
    fi
}

# ‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒
#                                                                    VALIDATION
# ‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒

check_compose_valid() {
    (( ${#DC[@]} )) || return 0
    log_step "Validating the merged compose configuration..."

    local out
    if out="$(cd "$SCRIPT_DIR" && "${DC[@]}" config -q 2>&1)"; then
        log_ok "The overlay stack merges cleanly."
    else
        fail "Compose rejected the merged configuration."
        printf '%s\n' "$out" >&2
    fi
}

# ‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒
#                                                                        LAUNCH
# ‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒

bring_up() {
    log_phase "START"

    if ! ask_confirm "Start the stack now?" y; then
        log_info "Nothing started. Run: ${DC[*]} up -d"
        return 1
    fi

    log_step "Pulling images..."
    ( cd "$SCRIPT_DIR" && "${DC[@]}" pull )

    log_step "Starting containers..."
    ( cd "$SCRIPT_DIR" && "${DC[@]}" up -d )

    log_ok "Containers are up."
    return 0
}

# Frigate prints a generated admin password on its first start, inside a block
# of asterisks. It does not always reprint it — see the reset_admin_password
# note if this comes up empty.
show_admin_password() {
    log_step "Waiting for Frigate to finish starting..."

    local attempt pw=""
    for attempt in $(seq 1 60); do
        : "$attempt"
        pw="$(cd "$SCRIPT_DIR" && "${DC[@]}" logs frigate 2>&1 \
              | grep -aoE 'Password:[[:space:]]*[^[:space:]*]+' \
              | tail -n1 | awk '{print $2}' || true)"
        [[ -n "$pw" ]] && break
        if (cd "$SCRIPT_DIR" && "${DC[@]}" logs frigate 2>&1 | grep -qa 'Capture process started'); then
            break
        fi
        sleep 2
    done

    if [[ -n "$pw" ]]; then
        log_phase "FIRST LOGIN"
        log_info "User:     admin"
        log_info "Password: $pw"
        log_warn "Change this at Settings > Users before creating any other account."
        log_next "On 0.17.2 any authenticated user can read the container log, and this password is in it."
    else
        log_info "No generated password in the log — normal if this instance has been started before."
        log_next "Locked out? Set auth.reset_admin_password: true in config.yml, restart, read the log, set it back."
    fi
}

report() {
    local ui_port; ui_port="$(env_get FRIGATE_UI_PORT)"; ui_port="${ui_port:-8971}"
    local rtsp_port; rtsp_port="$(env_get FRIGATE_RTSP_PORT)"; rtsp_port="${rtsp_port:-8554}"

    log_phase "NEXT"
    log_next "UI:        https://$(hostname -s 2>/dev/null || echo localhost).local:${ui_port}   (self-signed; the warning is expected)"
    log_next "Restream:  rtsp://<this-host>:${rtsp_port}/<camera>   and   /birdseye"
    log_next "Logs:      ${DC[*]} logs -f frigate"
    if [[ "$NETWORK" == "wireguard" ]]; then
        log_next "Tunnel:    ${DC[*]} exec wireguard wg show"
        log_next "Restarting the sidecar drops LAN cameras and the UI too, not only the remote ones."
        log_next "           Always follow it with: ${DC[*]} restart frigate"
    fi
}

# ‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒
#                                                                          MAIN
# ‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒

main() {
    parse_args "$@"
    check_for_root

    banner "FRIGATE SETUP" "$(host_model)"

    seed_if_missing

    log_phase "PREFLIGHT"
    check_docker
    check_profile
    check_detector_agreement
    check_devices
    check_storage
    check_jwt_secret
    check_wireguard
    check_compose_valid

    log_phase "SUMMARY"
    if (( FAILURES )); then
        log_err "$FAILURES problem(s) must be fixed before the stack will run."
        (( WARNINGS )) && log_warn "$WARNINGS warning(s) as well."
        exit 1
    fi

    if (( WARNINGS )); then
        log_warn "$WARNINGS warning(s). Nothing blocking."
    else
        log_ok "All checks passed."
    fi

    if (( CHECK_ONLY )); then
        log_info "--check given; stopping without starting anything."
        exit 0
    fi

    if bring_up; then
        show_admin_password
        report
        log_complete "FRIGATE IS RUNNING"
    fi
}

main "$@"
